# Generated by Django 5.1.6 on 2025-04-26 16:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(200)])),
                ('description', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner'], name='Task_task_owner_i_77907b_idx'), models.Index(fields=['name'], name='Task_task_name_1c81bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'owner'), name='unique_task_name_per_owner', violation_error_message='Task name must be unique per owner.')],
            },
        ),
    ]
